### ISSUE TITLE
Double scrollbar on Firefox

### ISSUE THREAD

**Issue by rumanbsl** [wslyvh/useWeb3#1]
OS: Mac BigSur
Browser: Firefox 92.0

![image](https://user-images.githubusercontent.com/13895272/133891868-a5252707-8e0b-4255-8658-35c7daf8b78a.png)

**Comment by wslyvh** [comment]
Thanks again for reporting. Apparently, I never tested on Firefox. 

And of course, also for fixing it and contributing. Very much appreciated 🙌 
PR merged
