### ISSUE TITLE
Wriggly - Submitting a Coding Challenge

### ISSUE THREAD

**Issue by siddDas98** [wslyvh/useWeb3#110]
Hello,

We would like to add our application to be a part of your web3 coding challenges. Wriggly is a web3 blockchain learning platform to practice Solidity based coding challenges to prepare for interviews.

Please find attached our .md file.

Thanks,

Sidd

[wriggly.md](https://github.com/wslyvh/useWeb3/files/11437149/wriggly.md)

**Comment by wslyvh** [comment]
Hi, please submit a PR with your md. Thank you!

**Comment by siddDas98** [comment]
Hey Wesley,

I'm getting this error when I try to push to my branch. I also used ssh to clone the repo. If you could help me, I'd really appreciate it.

![image](https://github.com/wslyvh/useWeb3/assets/124751797/9017a1fa-d927-4564-9a50-9fc991cd4b10)

Thanks,

Sidd

**Comment by wslyvh** [comment]
It seems like you haven't correctly configured your credentials.
What happens if you `ssh -T git@github.com` ?

Make sure to follow the steps at https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by siddDas98** [comment]
Followed the steps and still getting the same error. This is what I get when I try 
```ssh -T git@github.com```

![image](https://github.com/wslyvh/useWeb3/assets/124751797/83143583-069a-4c03-8796-c8418cfdc4f0)

**Comment by siddDas98** [comment]
Got it to work, thanks!
