### ISSUE TITLE
Request: adding BSC to contribution list

### ISSUE THREAD

**Issue by weiihann** [wslyvh/useWeb3#118]
BSC-Geth recently added "good first issue" tags. It'll be great if we can add them to the contribution list. If you need any support, please let me know. Thanks!

[BSC-Geth Repo](https://github.com/bnb-chain/bsc/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by wslyvh** [comment]
All the Ethereum execution and consensus client repos are on the contribution list.
I'd rather not add individual forks to the list as contributions to the main repos/clients are more valuable and can be merged downstream.
