### ISSUE TITLE
Add Juno.build

### ISSUE THREAD

**Issue by peterpeterparker** [wslyvh/useWeb3#124]
Hi 👋

I came across your website and I really liked its design (👍).

Therefore, I was thinking of submitting a PR to feature Juno ([website](https://juno.build/) / [GitHub](https://github.com/buildwithjuno/juno)). However, I'm not sure if it aligns with your interests or in which category it should be listed.

WDYT?

**Comment by wslyvh** [comment]
Hi David, thanks for checking in here! 

You're right that it currently doesn't really align within any categories. The focus is on educational resources, tutorials, videos, etc. While this seems interesting, I'm currently not planning to keep track of a tools overview. So just listing the website itself is less interesting, imo. What some other projects done in the past is to write educational content about their projects and submit that :)

Hope that helps

**Comment by wslyvh** [comment]
Closing this. Feel free to create a PR if you ever want to submit any educational resources :)

**Comment by peterpeterparker** [comment]
Thanks for your answer. Makes absolute sense!

I got few educational content:

- Build Juno with React: https://juno.build/blog/build-a-web3-app-with-react-js
- Build Juno with Angular: https://juno.build/blog/develop-an-angular-app-on-blockchain
- Build Juno with Vue: https://juno.build/blog/build-a-web3-app-with-vuejs

But, it's probably better to submit something like a all course I am guessing. So, I keep it in mind for the day such content will exist.

Thanks also for the tips about dapplist, I will have a look.

In anycase, you already had my GitHub star, useWeb3.xyz looks really cool 👍
