### ISSUE TITLE
Menu doesn't close when going from a category page to another category page on mobile

### ISSUE THREAD

**Issue by lendl** [wslyvh/useWeb3#14]
Repro steps
On mobile go to a Category page (for example 'Podcast').
Open the menu and go to another Category page (for example 'Code Challenge')
The menu stays open.
![image](https://user-images.githubusercontent.com/4136586/145071518-a7bfb3fd-322c-447d-9b88-57c0c4942427.png)

**Comment by wslyvh** [comment]
Yep. Can definitely be improved.

Do you want to submit a PR for it?
