### ISSUE TITLE
Detailed setup in README

### ISSUE THREAD

**Issue by alvaroserrrano** [wslyvh/useWeb3#16]
![Screen Shot 2022-01-02 at 6 00 19 PM](https://user-images.githubusercontent.com/43758471/147883326-74b1f4df-5e75-476a-b00d-52317945f908.png)

This project deserves more contributors, let's make it easier for people to get onboard. Some might move elsewhere if the setup  is not explained in detail. We should add things like `npm install` or `yarn` to install dependencies, how to setup the airtable API keys... It might seem obvious but doing so will increase this project's adoption

**Comment by wslyvh** [comment]
You're absolutely right, this isn't very contributor friendly.. 
Let me think about this and try to improve things + update developer documentation.

Thanks for sharing this!

**Comment by wslyvh** [comment]
Closing. Data is now stored on the repo itself. No longer using Airtable, so probably not relevant anymore.
