### ISSUE TITLE
Books: Books to add

### ISSUE THREAD

**Issue by franzihei** [wslyvh/useWeb3#17]
Here are a few ideas for books to add in the "learn through reading" section! :)

- Ethereum: Blockchains, Digital Assets, Smart Contracts, Decentralized Autonomous Organizations – 8. September 2016 - Henning Diedrich
- Lexon: Digital Contracts – 5. Oktober 2019 - Henning Diedrich
- Hands-On Smart Contract Development With Solidity and Ethereum: From Fundamentals to Deployment – 10. Dezember 2019 - Kevin Solorio, Randall Kanna, and Dave Hoover
- Introducing Ethereum and Solidity: Foundations of Cryptocurrency and Blockchain Programming for Beginners – 18. März 2017 - Chris Dannen **[maybe outdated by now]**

**Comment by wslyvh** [comment]
Thanks @franzihei 🙏

Added all, except for the last one. Development books get outdated quickly, unfortunately. You could probably say the same from some others on the list.

Also, there's a submit link on the site if you ever want to submit more resources 
https://www.useweb3.xyz/submit
