### ISSUE TITLE
Duplicate results on UX and Design tag

### ISSUE THREAD

**Issue by minimalsm** [wslyvh/useWeb3#3]
When filtering by the UX/Design tag I got duplicate results for Patrick's 'Solidity, Blockchain, and Smart Contract Course'

<img width="1656" alt="Screenshot 2021-10-11 at 19 17 30" src="https://user-images.githubusercontent.com/62268199/136836270-88adc926-5ea6-4fd8-8514-cac24e17d4ae.png">

**Comment by wslyvh** [comment]
Ah, I see. Thanks for reporting! 
It's actually added multiple times (as a video, tutorial and course). 
Resources weren't supposed to be in multiple categories initially. Will think about it..

**Comment by wslyvh** [comment]
Closing this issue. Duplicate items have been removed.
You still can't show items in multiple categories, but that's probably for the best. Otherwise items will just get added to most - showing the same items in each category.

https://www.useweb3.xyz/tags/ux%20&%20design
