### ISSUE TITLE
Add a movies category? 👀

### ISSUE THREAD

**Issue by saminacodes** [wslyvh/useWeb3#4]
Some suggestions for movies- all beginner friendly!
- [The Rise and Rise of Bitcoin](https://www.imdb.com/title/tt2821314/)
- [Banking on Bitcoin](https://www.imdb.com/title/tt5033790/)
- [Trust Machine](https://www.imdb.com/title/tt7407496/)
- [Cryptopia: Bitcoin, Blockchains and the Future of the Internet](https://www.imdb.com/title/tt9203586/)

**Comment by wslyvh** [comment]
Hi @saminacodes 

That's an interesting suggestion. I think I've only seen Banking on Bitcoin (long time ago).

Do you think these movies add value for developers? 
It probably makes sense for people to understand the history and fundamentals of the tech. Which I think most of these movies focus on?

**Comment by saminacodes** [comment]
I think it all accumulates for sure. I know for me starting out those documentaries helped a lot for understanding the big picture and getting a foot in on what is cryptocurrency, how does it work, the history, the risks, what still needs to be solved etc. I definitely value them.

**Comment by wslyvh** [comment]
Makes sense. It's up! :) 
https://www.useweb3.xyz/movies
