### ISSUE TITLE
Request: add a search bar

### ISSUE THREAD

**Issue by marciob** [wslyvh/useWeb3#5]
I think it would be nice to be able to search for things on website. These days I was thinking what courses related to The Graph exist, my first thought was to search it on on useWeb3, so I went to google: 'site:useweb3.xyz the graph'.

**Comment by wslyvh** [comment]
Great suggestion! Will definitely look into this

**Comment by wslyvh** [comment]
Added with the latest design update

E.g. https://www.useweb3.xyz/search?q=Security
